language: python

install:
  - pip install -r requirements.txt

env:
  global:
    - PYTHONPATH=$(pwd):$PYTHONPATH

script:
    - py.test --cov-report term --cov=test_all.py

after_success:
    - codecov
