language: python

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

env:
  global:
    - PYTHONPATH=$(pwd):$PYTHONPATH
    - FLARE_HOME=$(pwd)
    - CODECOV_TOKEN=17ea0d7e-6284-4834-8b03-506408fdd9d0

deploy:
    - provider: heroku
      api_key: $HEROKU_API_KEY
      app: flare34
      on:
          branch: main

script:
    - python3 -m pytest --cov=. test_all.py

after_success:
    - codecov

